### ISSUE TITLE
Infinite Loop 

### ISSUE THREAD

**Issue by pseud0** [alduron/JackBot#7]
Hello,
I noticed that if you attempt to reset the bot when you are not in a game the bot gets stuck in an infinite loop.

It seems to be because it gets to this part of the code and has a zero value -->

function Start-JackBox([int]$JackTarget){
    Write-Log -Message "Starting JackBox pack [$JackTarget]" -Type INF -Console -Log
    Set-JackboxState -JackTarget $JackTarget

To solve this I added before the Set-JackboxState line:    if(!$JackTarget -eq 0){

This ensures it doesn't get stuck if you !jackbot reset  when not in a game.

**Comment by alduron** [comment]
@TheyCallMeZ added the suggested fix, but after review I've moved the game check to the messaging switch, because this function should not be called in the first place. This also has the added benefit of ignoring the Start-Jackbox, Enter-DiscordChannel, and Set-DiscordStreamToggle that would have also been called in the event of a 0 game state flag. Thank you @pseud0 for submitting an issue and suggesting a fix. Always appreciated. :)
